[book]
authors = ["solareenlo"]
language = "ja"
multilingual = false
src = "src"
title = "緋色の習作"

[output.html]
theme = "src/theme"
additional-css = [
  "src/theme/solarized-light-hljs.css",
  "src/theme/solarized-dark-hljs.css",
]
additional-js = [
  "src/theme/theme-solarized_dark.js",
  "src/theme/theme-solarized_light.js",
]
git-repository-url = "https://github.com/solareenlo/A_Study_in_Scarlet"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/solareenlo/A_Study_in_Scarlet/edit/main/{path}"
mathjax-support = true
copy-fonts = true

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = true
